#define LOW_BATTERY_LEVEL 15
#define MEDIUM_BATTERY_LEVEL 45
#define HIGH_BATTERY_LEVEL 75

#define HUMIDITY_THRESHOLD 100
#define HUMIDITY_TOLERANT_STRING "NEAR OPTIMAL"
#define HUMIDITY_BELOW_STRING "BELOW OPTIMAL"
#define HUMIDITY_ABOVE_STRING "ABOVE OPTIMAL"

#define LAST_WATERED_PREFIX_STRING "LAST WATERED"
#define LAST_WATERED_POSTFIX_STRING "HOURS AGO"

#define MEASUREMENT_DELAY 1000