#define HUMIDITY_SENSOR_PIN 0
#define HUMIDITY_POWER_PIN 13
#define WATER_TANK_SENSOR_PIN 6
#define WATER_TANK_POWER_PIN 7
#define SELF_SUPPLY_SENSOR_PIN 1

#define LEFT_BUTTON_PIN 8
#define RIGHT_BUTTON_PIN 9
#define CENTER_BUTTON_PIN 10

#define BUZZER_PIN_8
